server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/learninjavagithub/spring-boot
          #username: uname
          #password: password
          search-paths:
           - 'price*'
        encrypt:
          enabled: false
          